import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  container: {
    flex: 0,
    backgroundColor: '$white',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  inputStyle: {
    display: 'flex',
    flex: 0,
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#E9EAEB',
    color: '#333333',
    borderRadius: 0,
  },
  minusIcon: {
    height: 30,
    width: 30,
    margin: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E9EAEB',
    color: '#333333',
    borderRadius: 0,
    padding: 0,
  },
  minusText: {
    alignItems: 'center',
    justifyContent: 'center',
    color: '#333333',
    fontSize: 8,
    margin: 0,
  },
  plusIcon: {
    height: 30,
    width: 30,
    margin: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E9EAEB',
    color: '#333333',
    borderRadius: 0,
    padding: 0,
  },
  plusText: {
    alignItems: 'center',
    justifyContent: 'center',
    color: '#333333',
    fontSize: 8,
    margin: 0,
  },
});
