import {Dimensions} from 'react-native';
import EStyleSheet from 'react-native-extended-stylesheet';
export default EStyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '$white',
    flexDirection: 'column',
  },
  titleContainer: {
    padding: 16,
    backgroundColor: '$white',
  },
  title: {
    fontSize: 14,
    fontWeight: '600',
    color: '$black',
  },
  listWrapper: {
    paddingTop: 20,
    backgroundColor: '$white',
    width: '100%',
    // justifyContent: 'flex-start',
    // alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  itemWrapper: {
    width: '100%',
    flexDirection: 'row',
    height: 100,
    marginBottom: 20,
  },
  itemInner: {
    flexDirection: 'row',
    width: '100%',
    height: '100%',
    paddingHorizontal: 10,
  },
  imageContainer: {
    flex: 2,
    position: 'relative',
  },
  imageStyle: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
    position: 'relative',
  },
  infoContainer: {
    flex: 7,
    flexDirection: 'column',
    paddingLeft: 12,
    justifyContent: 'space-around',
  },
  flexRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  ratingContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  itemName: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '400',
    color: '$black',
  },
  itemPrice: {
    fontSize: 14,
    fontWeight: '500',
    color: '$black',
  },
  itemDiscountPrice: {
    fontSize: 13,
    color: '$lightGray',
    fontWeight: '200',
  },
  ratingPoint: {
    fontSize: 11,
    color: '$lightGray',
    marginLeft: 10,
    fontWeight: '300',
  },
  itemBadge: {
    position: 'absolute',
    bottom: 10,
    left: 10,
    justifyContent: 'center',
    alignItems: 'center',
    // minWidth: 50,
    paddingVertical: 5,
    paddingHorizontal: 3,
    borderRadius: 5,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '500',
    color: '$white',
  },
  progressBar: {
    height: 16,
    borderRadius: 10,
    position: 'relative',
  },
  progressBarText: {
    width: '100%',
    position: 'absolute',
    top: 1,
    alignSelf: 'center',
    color: '#fff',
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '500',
  },
  countDownItem: {
    borderRadius: 4,
    minWidth: 24,
    minHeight: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  countDownItemText: {
    fontSize: 13,
  },
  countDownContainer: {
    flexDirection: 'row',
    flex: 2,
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingLeft: 6,
  },
});
