/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-southeast-1",
  "aws_cognito_identity_pool_id": "ap-southeast-1:04513a47-2cf0-47fe-a766-606510e6be33",
  "aws_cognito_region": "ap-southeast-1",
  "aws_user_pools_id": "ap-southeast-1_dSSJM8sQe",
  "aws_user_pools_web_client_id": "2cjbb1o65lh7upb6gppdb0ddp8",
  "oauth": {
    "domain": "prostylee-staging.auth.ap-southeast-1.amazoncognito.com",
    "scope": [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin"
    ],
    "redirectSignIn": "prostylee://",
    "redirectSignOut": "prostylee://",
    "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_appsync_graphqlEndpoint": "https://b5rhkorgpnak5hv5j5e632mmsi.appsync-api.ap-southeast-1.amazonaws.com/graphql",
  "aws_appsync_region": "ap-southeast-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_user_files_s3_bucket": "psmedia224241-staging",
  "aws_user_files_s3_bucket_region": "ap-southeast-1"
};
export default awsmobile;